# Generated by Django 5.0.6 on 2024-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="Lorem Ipsum "),
        ),
    ]
